### ISSUE TITLE
Support Python 2.7

### ISSUE THREAD

**Issue by wvengen** [fnl/segtok#1]
Thanks for this nice module!

I'd like to use segtok with Scrapy, which doesn't support Python 3 yet. Merely removing `: str` in method definitions made it work for me. Would you consider supporting Python 2?

**Comment by fnl** [comment]
You are most welcome! Sure, in principal I see no reason why not. Did you run the tests and could you submit a PR? Let me know if I can be of help and thanks to you!

**Comment by wvengen** [comment]
Thanks! I've put it on my todo list.

**Comment by fnl** [comment]
Great, thanks! Just a word of warning maybe: Even through at a first glance it seems trivial, usually, porting back to Py2.x requires more work than might be anticipated at first, with four main issues: (1) The command-line interfaces break, (2) file-IO, string, and exception handling has changed, (3) in Py3 essentially everything now is an iterator/generator, and (4) ensuring consistent, correct Unicode support is a pain in certain places with Python 2.x (my main reason why I have stopped using Py 2.x long ago, btw, and never again have seen that pesky `UnicodeError` popping up...). In this case, _probably_ only (1) and (4) need to be addressed, but I usually assume the worst case, because that turns out more often than not to be the real case... In any case, if you need help, let me know!

**Comment by fnl** [comment]
Solved - thanks to @kmike with PRs #2 and #3

**Comment by wvengen** [comment]
Thanks!
